In [3]:
import numpy as np;

In [4]:
def get_cycles(n, p, m):
    l = [(p * i) % n for i in range(n)]
    return l

In [5]:
def color_table(n, p, m):
    l = get_cycles(n, p, m)
    colors = [[-1 for i in range(n)] for j in range(n)]
    cnt = 1
    for i in range(n):
        for j in range(n):
            if (i == j):
                continue
            if (colors[i][j] >= 0):
                continue
            pi = i
            pj = j
            while (colors[pi][pj] < 0):
                colors[pi][pj] = cnt
                colors[pj][pi] = cnt
                pi = l[pi]
                pj = l[pj]
            cnt += 1
    return colors

In [75]:
def sum_table(n, p, m, begin):
    l = get_cycles(n, p, m)
    colors = [[-1 for i in range(n)] for j in range(n)]
    frow = [-n for i in range(n)]
    
    nex = 0
    col = n - 1
    row = begin
    for i in range((n - 1) // 2):
        while (colors[row][col] != 0):
            colors[row][col] = nex
            if (row == 0):
                if (frow[col] != -n and frow[col] != nex and frow[col] != -nex):
                    print("some shit")
                frow[col] = -nex
            row = (row + 1) % n;
            col = (col + 1) % n;
            if (row > col):
                row, col = col, row
            nex = (nex + 1) % n;
        if (frow[row] == -n):
            frow[row] = col
        else:
            if (frow[row] != col and frow[row] != -col):
                print("some shit 2")
        if (frow[col] == -n):
            frow[col] = row
        else:
            if (frow[col] != row and frow[col] != -row):
                print("some shit 3")
        row = 0
        col = 1
        print(frow)
        while (col < n and frow[col] < 0):
            col += 1
        if (col == n):
            if (i != ((n - 1) // 2) - 1):
                print("Alarm!")
            break
        else:
            nex = frow[col]
    return colors

In [64]:
def test(p, m):
    n = 1
    for i in range(m):
        n *= p
    n -= 1
    
    #colors = color_table(n, p, m)
    for i in range(1, n - 1):
        colors = sum_table(n, p, m, i)
        print(np.array(colors))
        print()

In [81]:
test(2, 4)

[-15, 14, -1, -15, -15, -15, -15, -15, -15, -15, -15, -15, -15, -14, 1]
some shit
some shit 2
[-15, -14, -1, -15, -15, -15, -15, -15, -15, -15, -15, -15, -15, -14, -13]
Alarm!
[[-1 14  1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 14 13]
 [-1 -1  0  2 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1  0]
 [-1 -1 -1  1  3 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1]
 [-1 -1 -1 -1  2  4 -1 -1 -1 -1 -1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1  3  5 -1 -1 -1 -1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1 -1  4  6 -1 -1 -1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1 -1 -1  5  7 -1 -1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1 -1 -1 -1  6  8 -1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1 -1 -1 -1 -1  7  9 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1 -1 -1 -1 -1 -1  8 10 -1 -1 -1]
 [-1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1  9 11 -1 -1]
 [-1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 10 12 -1]
 [-1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 11 13]
 [-1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 12]
 [-1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1]]

[-15, -15, 14, -1, -15, -15, -15, -15, -15, -15, -15, -15, -13, -15, 2]
[-15, 3, -14, -1, -15, -15, -1